services:
  postgres:
    image: postgres:16
    container_name: postgreSQL
    environment:
      POSTGRES_DB: "celosia-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pgdata-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata-volume:
    name: pgdata